### ISSUE TITLE
Building astropy fails with ImportError: Numpy version 1.13.0 or later must be installed to use Astropy

### ISSUE THREAD

**Issue by paul-gauthier** [aorwall/SWE-bench-docker#15]
The other failure I am getting is when running:

```
./scripts/build_docker_images.sh docker aorwall astropy__astropy
```

It fails like this:

```
#13 [stage-0  7/11] RUN pip install -e .[test]
#13 0.605 Obtaining file:///opt/astropy__astropy
#13 0.609   Installing build dependencies: started
#13 2.381   Installing build dependencies: finished with status 'done'
#13 2.382   Checking if build backend supports build_editable: started
#13 2.554   Checking if build backend supports build_editable: finished with status 'done'
#13 2.555   Getting requirements to build editable: started
#13 4.113   Getting requirements to build editable: finished with status 'error'
#13 4.122   error: subprocess-exited-with-error
#13 4.122
#13 4.122   × Getting requirements to build editable did not run successfully.
#13 4.122   │ exit code: 1
#13 4.122   ╰─> [28 lines of output]
#13 4.122       Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
#13 4.122       warning: no previously-included files found matching '*.pyc'
#13 4.122       warning: no previously-included files found matching '*.o'
#13 4.122       no previously-included directories found matching 'build'
#13 4.122       no previously-included directories found matching 'astropy_helpers/tests'
#13 4.122       Traceback (most recent call last):
#13 4.122         File "/opt/pyenv/versions/3.9.19/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#13 4.122           main()
#13 4.122         File "/opt/pyenv/versions/3.9.19/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#13 4.122           json_out['return_val'] = hook(**hook_input['kwargs'])
#13 4.122         File "/opt/pyenv/versions/3.9.19/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
#13 4.122           return hook(config_settings)
#13 4.122         File "/tmp/pip-build-env-9h67qvlr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
#13 4.122           return self.get_requires_for_build_wheel(config_settings)
#13 4.122         File "/tmp/pip-build-env-9h67qvlr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#13 4.122           return self._get_build_requires(config_settings, requirements=['wheel'])
#13 4.122         File "/tmp/pip-build-env-9h67qvlr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
#13 4.122           self.run_setup()
#13 4.122         File "/tmp/pip-build-env-9h67qvlr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
#13 4.122           super().run_setup(setup_script=setup_script)
#13 4.122         File "/tmp/pip-build-env-9h67qvlr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
#13 4.122           exec(code, locals())
#13 4.122         File "<string>", line 26, in <module>
#13 4.122         File "/opt/astropy__astropy/astropy/__init__.py", line 118, in <module>
#13 4.122           _check_numpy()
#13 4.122         File "/opt/astropy__astropy/astropy/__init__.py", line 112, in _check_numpy
#13 4.122           raise ImportError(msg)
#13 4.122       ImportError: Numpy version 1.13.0 or later must be installed to use Astropy
#13 4.122       [end of output]
#13 4.122
#13 4.122   note: This error originates from a subprocess, and is likely not a problem with pip.
#13 4.124 error: subprocess-exited-with-error
#13 4.124
#13 4.124 × Getting requirements to build editable did not run successfully.
#13 4.124 │ exit code: 1
#13 4.124 ╰─> See above for output.
#13 4.124
#13 4.124 note: This error originates from a subprocess, and is likely not a problem with pip.
#13 ERROR: process "/bin/sh -c pip install -e .[test]" did not complete successfully: exit code: 1
------
 > [stage-0  7/11] RUN pip install -e .[test]:
#13 4.122       [end of output]
```

**Comment by aorwall** [comment]
I also get errors when I try to build astropy now. My guess is that a dependency without a explicitly set version was upgraded since I first built the images. Can't figure out which though. 

Seems like the already pushed Docker images still works though (:crossed_fingers: ).
