### ISSUE TITLE
Getting setup working

### ISSUE THREAD

**Issue by andrewliu08** [aorwall/SWE-bench-docker#26]
Dumb question but I'm getting errors when running the basic `run_instance_tests.py`. Also, I'm unable to pull images using the `./scripts/pull_docker_images.sh` script. Anything I'm doing wrong here?

Error output for `run_instance_tests.py`:
```shell
> python run_instance_tests.py --instance_id django__django-15202

Traceback (most recent call last):
  File "/Users/sashank/projects/SWE-bench-docker/run_instance_tests.py", line 146, in <module>
    output = asyncio.run(main(**vars(args)))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sashank/projects/SWE-bench-docker/run_instance_tests.py", line 123, in main
    tasks = get_eval_refs(swe_bench_tasks)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/swebench/metrics/getters.py", line 138, in get_eval_refs
    data = load_dataset(data_path_or_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/load.py", line 2592, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/load.py", line 2264, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/load.py", line 1915, in dataset_module_factory
    raise e1 from None
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/load.py", line 1897, in dataset_module_factory
    ).get_module()
      ^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/load.py", line 1213, in get_module
    dataset_readme_path = cached_path(
                          ^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/utils/file_utils.py", line 201, in cached_path
    output_path = get_from_cache(
                  ^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/utils/file_utils.py", line 649, in get_from_cache
    with FileLock(lock_path):
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/sashank/.pyenv/versions/swebench/lib/python3.12/site-packages/datasets/utils/_filelock.py", line 42, in __init__
    super().__init__(lock_file, *args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Error output for `./scripts/pull_docker_images.sh`:
```shell
> ./scripts/pull_docker_images.sh docker exponent

Pulling Docker image: exponent/swe-bench-astropy_astropy-testbed:1.3
Error response from daemon: pull access denied for exponent/swe-bench-astropy_astropy-testbed, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling Docker image: exponent/swe-bench-astropy_astropy-testbed:4.3
Error response from daemon: pull access denied for exponent/swe-bench-astropy_astropy-testbed, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling Docker image: exponent/swe-bench-astropy_astropy-testbed:5.1
Error response from daemon: pull access denied for exponent/swe-bench-astropy_astropy-testbed, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling Docker image: exponent/swe-bench-astropy_astropy-testbed:5.2
Error response from daemon: pull access denied for exponent/swe-bench-astropy_astropy-testbed, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling Docker image: exponent/swe-bench-django_django-testbed:1.10
Error response from daemon: pull access denied for exponent/swe-bench-django_django-testbed, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling Docker image: exponent/swe-bench-django_django-testbed:1.11
```

**Comment by aorwall** [comment]
Looks like you set your own docker namespace. If you didn’t build the docker images yourself it’s probably better to test with my built ones. So you can try with 

`> ./scripts/pull_docker_images.sh docker aorwall`
