### ISSUE TITLE
Problems with logs dirs?

### ISSUE THREAD

**Issue by paul-gauthier** [aorwall/SWE-bench-docker#31]
I am seeing errors from some of the containers as they try and access the logs dirs. I am pulling all the latest images, not using/building any of them locally at the moment.

Am I doing something wrong? Or is this a bug in some of these images?

For example:

```
2024-06-20 19:40:33,320 - INFO - Instance ID: pydata__xarray-5131
Testbed: pydata__xarray__0.12
Log dir: /home/swe-bench/logs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 86, in <module>
    main(
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 30, in main
    with TaskEnvContextManager(
  File "/home/swe-bench/swebench_docker/context_manager.py", line 139, in __enter__
    output = self.exec("python --version".split())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swe-bench/swebench_docker/context_manager.py", line 53, in __call__
    self.logger.write(f"Command: {' '.join(cmd)}", level=DEBUG)
  File "/home/swe-bench/swebench_docker/context_manager.py", line 30, in write
    with open(self.log_file, mode) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/swe-bench/logs/pydata__xarray-5131.none.eval.log'
```

Or...

```
2024-06-20 19:36:01,426 - INFO - Instance ID: pytest-dev__pytest-7220
Testbed: pytest-dev__pytest__5.4
Log dir: /opt/logs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 86, in <module>
    main(
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 30, in main
    with TaskEnvContextManager(
  File "/home/swe-bench/swebench_docker/context_manager.py", line 139, in __enter__
    output = self.exec("python --version".split())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swe-bench/swebench_docker/context_manager.py", line 53, in __call__
    self.logger.write(f"Command: {' '.join(cmd)}", level=DEBUG)
  File "/home/swe-bench/swebench_docker/context_manager.py", line 30, in write
    with open(self.log_file, mode) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/logs/pytest-dev__pytest-7220.none.eval.log'
```

**Comment by aorwall** [comment]
I’m not sure what’s happening. Same thing if you mount to a new log directory with write access for all users?

**Comment by yingweima2022** [comment]
Hi, I also encountered this problem. It was fine before. Did you solve it?

**Comment by yingweima2022** [comment]
I deleted and pulled all the dockers again but it still doesn't work. some instances are ok, but some are wrong.

**Comment by paul-gauthier** [comment]
This appears to be a problem with my own code. I think I may have been providing a log dir to the docker container that was getting prematurely deleted, while the container still expected it to be there. I seem to have resolved these errors by ensuring the dir isn't deleted.

**Comment by qingping95** [comment]
@paul-gauthier Hello, I have not changed the code of SWE-bench-docker, but the problem still occurs. Could you tell me which part of the code you modified that caused this problem? 

Thanks!

**Comment by paul-gauthier** [comment]
As I mentioned, I also did not make changes to SWE-bench-docker. I was calling `run_docker_evaluation` with a `log_dir` that wasn't guaranteed to survive as long as the docker image ran. I'm assuming it was being deleted due to a race condition, and then the docker instance reacted to that as a PermError.

**Comment by qingping95** [comment]
@paul-gauthier My env is working now, even though I didn't do anything. This is so weird, but thanks for your response. :)
