### ISSUE TITLE
log_dir Permission Denied

### ISSUE THREAD

**Issue by GCVulnerability** [aorwall/SWE-bench-docker#36]
I have used the run_evaluate.py with args clarified in README.
However, I do not have permission to use sudo.
So my eval got the ERROR below, even I have set the log_dir to a dir that I have the permission to change it.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 86, in <module>
    main(
  File "/home/swe-bench/swebench_docker/evaluate_instance.py", line 30, in main
    with TaskEnvContextManager(
  File "/home/swe-bench/swebench_docker/context_manager.py", line 139, in __enter__
    output = self.exec("python --version".split())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swe-bench/swebench_docker/context_manager.py", line 53, in __call__
    self.logger.write(f"Command: {' '.join(cmd)}", level=DEBUG)
  File "/home/swe-bench/swebench_docker/context_manager.py", line 30, in write
    with open(self.log_file, mode) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/logs/astropy__astropy-6938.agentless.eval.log'

**Comment by aorwall** [comment]
Hmm, might be the same as #31. But this repo isn't maintained any longer as the SWE-bench team's own containerized solution is more stable. My suggestion is to use that one or try my hosted version at https://eval.moatless.ai/.

**Comment by GCVulnerability** [comment]
> SWE

Thanks for your reply. But I could not construct the docker by fowllowing SWE-bench team because of our county's limitation to Docker Hub.
I have noticed that the hoted version at https://eval.moatless.ai/ can only be used once per day.
If you could open up more times to me, I would greatly appreciate it.
